import { Listing, Booking, User, EmailNotification } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_renter_1',
    name: 'Sophia Chen',
    email: 'sophia.chen@example.com',
    role: 'renter',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
  },
  {
    id: 'usr_host_ghana',
    name: 'Kwame Mensah',
    email: 'kwame.mensah@ghanaluxury.com',
    role: 'host',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=250&q=80',
  },
  {
    id: 'usr_host_1',
    name: 'Alexander Wright',
    email: 'alexander.wright@luxuryrentals.com',
    role: 'host',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
  },
  {
    id: 'usr_admin_1',
    name: 'System Admin',
    email: 'admin@fieldstay.com',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=250&q=80',
  },
];

export const INITIAL_LISTINGS: Listing[] = [
  {
    id: 'apt_accra_101',
    hostId: 'usr_host_ghana',
    hostName: 'Kwame Mensah',
    hostEmail: 'kwame.mensah@ghanaluxury.com',
    hostAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=250&q=80',
    title: 'Cantonments Luxury Villa & Pool Suite',
    description: 'Ultra-modern architectural villa in premier Cantonments enclave, Accra. Features private swimming pool, sun deck, 24/7 solar backup security power, smart air conditioning, and chef kitchen.',
    city: 'Accra',
    neighborhood: 'Cantonments',
    address: '14 Rangoon Lane, Cantonments, Accra',
    pricePerNight: 320,
    bedrooms: 3,
    bathrooms: 3,
    maxGuests: 6,
    photos: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'approved',
    createdAt: '2026-07-10T10:00:00Z',
    amenities: ['Private Pool', '24/7 Solar Backup Power', 'Hyper-fast Fiber Wi-Fi', 'Gated Security', 'Gym', 'Airport Pickup'],
    blockedDates: ['2026-08-05', '2026-08-06', '2026-08-07'],
  },
  {
    id: 'apt_accra_102',
    hostId: 'usr_host_ghana',
    hostName: 'Kwame Mensah',
    hostEmail: 'kwame.mensah@ghanaluxury.com',
    hostAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=250&q=80',
    title: 'Airport Residential Sky Suite',
    description: 'Breathtaking penthouse apartment minutes from Kotoka International Airport. Floor-to-ceiling glass windows overlooking Accra skyline, rooftop lounge, and private concierge.',
    city: 'Accra',
    neighborhood: 'Airport Residential',
    address: '8 Liberation Road, Accra',
    pricePerNight: 260,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    photos: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'approved',
    createdAt: '2026-07-12T14:30:00Z',
    amenities: ['Skyline Terrace', 'Rooftop Infinity Pool', 'Smart Home', 'Underground Parking', '24/7 Concierge'],
    blockedDates: [],
  },
  {
    id: 'apt_kumasi_201',
    hostId: 'usr_host_ghana',
    hostName: 'Kwame Mensah',
    hostEmail: 'kwame.mensah@ghanaluxury.com',
    hostAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=250&q=80',
    title: 'Royal Ahodwo Executive Residency',
    description: 'Serene executive retreat in the green hills of Ahodwo, Kumasi. Blends royal Ashanti woodwork detailing with modern luxury amenities, private garden courtyard, and high-speed Wi-Fi.',
    city: 'Kumasi',
    neighborhood: 'Ahodwo',
    address: '22 Cedar Avenue, Ahodwo, Kumasi',
    pricePerNight: 190,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    photos: [
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'approved',
    createdAt: '2026-07-18T09:00:00Z',
    amenities: ['Garden Courtyard', 'Generator Backup', 'Dedicated Workspace', 'Chef Kitchen', 'Breakfast included'],
    blockedDates: ['2026-08-12', '2026-08-13'],
  },
  {
    id: 'apt_takoradi_301',
    hostId: 'usr_host_ghana',
    hostName: 'Kwame Mensah',
    hostEmail: 'kwame.mensah@ghanaluxury.com',
    hostAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=250&q=80',
    title: 'Beach Road Oceanview Villa Takoradi',
    description: 'Coastal paradise residence along Beach Road, Takoradi. Panoramic views of the Atlantic ocean, sea breeze balcony, infinity pool, and private access to pristine shores.',
    city: 'Takoradi',
    neighborhood: 'Beach Road',
    address: '5 Atlantic Drive, Beach Road, Takoradi',
    pricePerNight: 220,
    bedrooms: 3,
    bathrooms: 2.5,
    maxGuests: 5,
    photos: [
      'https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'approved',
    createdAt: '2026-07-20T16:00:00Z',
    amenities: ['Direct Oceanfront View', 'Private Balcony', 'Swimming Pool', 'Solar Generator', 'Barbecue Patio'],
    blockedDates: [],
  },
  {
    id: 'apt_101',
    hostId: 'usr_host_1',
    hostName: 'Alexander Wright',
    hostEmail: 'alexander.wright@luxuryrentals.com',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    title: 'The Modern Minimalist Loft',
    description: 'Sun-drenched penthouse featuring double-height ceiling windows, exposed concrete architectural elements, private rooftop deck, and custom Italian walnut cabinetry.',
    city: 'New York',
    neighborhood: 'SoHo',
    address: '482 Broome St, New York, NY 10013',
    pricePerNight: 350,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    photos: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'approved',
    createdAt: '2026-06-10T14:30:00Z',
    amenities: ['High-speed Wi-Fi', 'Private Balcony', 'Washer & Dryer', 'Central AC', 'Chef Kitchen'],
    blockedDates: ['2026-08-01', '2026-08-02', '2026-08-03'],
  },
  {
    id: 'apt_102',
    hostId: 'usr_host_1',
    hostName: 'Alexander Wright',
    hostEmail: 'alexander.wright@luxuryrentals.com',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    title: 'Haussmannian Elegance near Canal Saint-Martin',
    description: 'Classic Parisian apartment featuring intricate crown moldings, chevron parquet flooring, marble fireplaces, and cast-iron balconies.',
    city: 'Paris',
    neighborhood: 'Le Marais',
    address: '24 Rue de Turenne, 75004 Paris',
    pricePerNight: 280,
    bedrooms: 2,
    bathrooms: 1,
    maxGuests: 3,
    photos: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'approved',
    createdAt: '2026-06-15T09:12:00Z',
    amenities: ['Espresso Machine', 'Hyper-fast Fiber Internet', 'Balcony', 'Sonos Sound System'],
    blockedDates: [],
  }
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk_201',
    listingId: 'apt_accra_101',
    listingTitle: 'Cantonments Luxury Villa & Pool Suite',
    listingCity: 'Accra',
    listingPhoto: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=600&q=80',
    renterId: 'usr_renter_1',
    renterName: 'Sophia Chen',
    renterEmail: 'sophia.chen@example.com',
    hostId: 'usr_host_ghana',
    hostEmail: 'kwame.mensah@ghanaluxury.com',
    startDate: '2026-08-05',
    endDate: '2026-08-08',
    nightCount: 3,
    totalPrice: 960,
    status: 'accepted',
    createdAt: '2026-07-22T10:30:00Z',
    notes: 'Visiting Accra for business & leisure. Excited for the stay!',
  }
];

export const INITIAL_EMAILS: EmailNotification[] = [
  {
    id: 'em_301',
    recipientEmail: 'kwame.mensah@ghanaluxury.com',
    recipientRole: 'host',
    subject: '🔔 New Booking Request for Cantonments Luxury Villa',
    body: 'Hi Kwame, Sophia Chen submitted a stay request for Aug 5 - Aug 8 in Accra (3 nights, Total: $960). Log into your host portal to respond.',
    timestamp: '2026-07-22T10:30:00Z',
    type: 'booking_request',
    read: true,
  },
  {
    id: 'em_302',
    recipientEmail: 'sophia.chen@example.com',
    recipientRole: 'renter',
    subject: '🎉 Booking Confirmed! Cantonments Luxury Villa, Accra',
    body: 'Great news Sophia! Host Kwame Mensah has accepted your booking request in Cantonments, Accra for Aug 5 - Aug 8. Check your booking history for details.',
    timestamp: '2026-07-22T11:05:00Z',
    type: 'booking_accepted',
    read: false,
  }
];
